CREATE INDEX Eintrittsindex ON Pers(eindat);

EXPLAIN PLAN FOR
SELECT UPPER(name), UPPER(beruf)
FROM pers
WHERE TO_CHAR(eindat, 'YY') = '94';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR
SELECT UPPER(name), UPPER(beruf)
FROM pers
WHERE eindat BETWEEN '01.01.94'
AND '31.12.94';

EXPLAIN PLAN FOR
SELECT UPPER(name), UPPER(beruf)
FROM pers
WHERE EXTRACT(YEAR FROM to_DATE(eindat, 'DD/MM/YY')) = 2094;
